on:
  push:
    branches:
      - master

jobs:
  auto_increment_version:
    runs-on: ubuntu-latest
    name: Auto increment package version
    steps:
      - name: Checkout Package
        id: checkoutPackage
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Update Version
        id: updateVersion
        run: PACKAGE_VERSION=$(npm version patch --allow-same-version false --git-tag-version false -m "Automated version update for %s")
          echo '::set-output name=PACKAGE_VERSION::${PACKAGE_VERSION}'
      - name: Echo Version
        id: echoVersion
        run: echo '${GITHUB_REPOSITORY}-${{ steps.updateVersion.output.PACKAGE_VERSION }}''
