on:
  push:
    branches:
      - master

jobs:
  auto_increment_version:
    runs-on: ubuntu-latest
    name: Auto increment package version
    steps:
      - name: Checkout Package
        id: checkoutPackage
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Update Version
        id: updateVersion
        run: echo "::set-output name=PACKAGE_VERSION::green"
      - name: Echo Version
        id: echoVersion
        run: echo "$GITHUB_REPOSITORY-${{ steps.updateVersion.output.PACKAGE_VERSION }}"
