on:
  push:
    branches:
      - master

jobs:
  auto_increment_version:
    runs-on: ubuntu-latest
    name: Auto increment package version
    steps:
      - name: Checkout and update package version
        id: checkoutAndUpdateVersion
        uses: actions/checkout@v2
        with:
          access-token: ${{ secrets.ACTIONS_TOKEN }}
        run: npm version patch -m "Feature version update %s"
        run: git push --force
        run: ::set-output name=PACKAGE_VERSION::$(npm version patch --allow-same-version false --git-tag-version false -m "Automated version update for %s")
        run: ::set-output name=PACKAGE_NAME::$(sed -nE 's/^\s*"name": "(.*?)",$/\1/p' package.json)
        run: echo ${PACKAGE_NAME}-${PACKAGE_VERSION}
