on:
  push:
    branches:
      - master

jobs:
  auto_bump_version_job:
    runs-on: ubuntu-latest
    name: A job to bump the version
    if: "startsWith(github.event.head_commit.message, 'FEAT:')"
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.name 'kephman'
      - run: git config --global user.email 'kepher@gmail.com'
      - run: npm version patch -m "Feature version update %s"
      - run: git push
