on:
  push:
    branches:
      - master

jobs:
  auto_increment_version:
    runs-on: ubuntu-latest
    name: Auto increment package version
    steps:
      - name: Checkout Package
        id: checkoutPackage
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Update Version
        id: updateVersion
        run: echo ::set-output name=PACKAGE_VERSION::$(npm version patch --allow-same-version false --git-tag-version false -m "Automated version update for %s")
      - name: Checkout Branch
        id: checkoutBranch
        run: |
          BRANCH_NAME=$GITHUB_REPOSITORY-${{ steps.updateVersion.outputs.PACKAGE_VERSION }}
          eval "git checkout ${BRANCH_NAME} || git checkout -b ${BRANCH_NAME}"
          echo ::set-output name=BRANCH_NAME::$(echo ${BRANCH_NAME})
      - name: Commit Changes
        id: commitChanges
        run: |
          eval "git commit -a -m \"AUTO: Version update for ${{ steps.updateVersion.outputs.PACKAGE_VERSION }}\""
          eval "git push --set-upstream origin ${{ steps.checkoutBranch.outputs.BRANCH_NAME }}"
      - name: Create Pull Request
        id: createPull
        uses: kephman/auto-version-node@v1.0.3
        with:
          access-token: ${{ secrets.ACTIONS_TOKEN }}
          branch-name: ${{ steps.checkoutBranch.outputs.BRANCH_NAME }}
          package-version: ${{ steps.updateVersion.outputs.PACKAGE_VERSION }}
