on:
  push:
    branches:
      - master

jobs:
  auto_increment_version:
    runs-on: ubuntu-latest
    name: Auto increment package version
    steps:
      - name: Checkout Package
        id: checkoutPackage
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Update Version
        id: updateVersion
        run: echo '::set-output name=PACKAGE_VERSION::$(npm version patch --allow-same-version false --git-tag-version false -m "Automated version update for %s")'
      - name: Setup Commit
        id: setupCommit
        run: BRANCH_NAME=$GITHUB_REPOSITORY-${{ steps.updateVersion.outputs.PACKAGE_VERSION }}
          echo '::set-output name=BRANCH_NAME_PUSHED::$BRANCH_NAME'
      - name: Echo Version
        id: echoVersion
        run: echo "${{ steps.setupCommit.outputs.BRANCH_NAME_PUSHED }}"
