on:
  push:
    branches:
      - master

jobs:
  auto_increment_version:
    runs-on: ubuntu-latest
    name: Auto increment package version
    steps:
      - name: Checkout Package
        id: checkoutPackage
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Update Version
        id: updateVersion
        run: |
          PACKAGE_VERSION=$(npm version patch --allow-same-version false --git-tag-version false -m "Automated version update for %s")
          echo ::set-output name=PACKAGE_VERSION::$(echo ${PACKAGE_VERSION})
      - name: Verify Branch
        id: verifyBranch
        run: |
          BRANCH_NAME=${{ github.event.repository.name }}-${{ steps.updateVersion.outputs.PACKAGE_VERSION }}
          echo ::set-output name=BRANCH_NAME::$(echo ${BRANCH_NAME})
          BRANCH_EXISTS=$($(eval "git show-ref --verify --quiet refs/heads/${BRANCH_NAME}") && echo true || echo false)
          echo ::set-output name=BRANCH_EXISTS::$(echo ${BRANCH_EXISTS})
      - name: Commit New Branch
        id: commitNewBranch
        if: ${{ steps.verifyBranch.outputs.BRANCH_EXISTS == 'false' }}
        run: |
          git config --global user.name "kephman"
          git config --global user.email "kepher@gmail.com"
          git checkout -b ${{ steps.verifyBranch.outputs.BRANCH_NAME }}
          git commit -am "AUTO: Version update for ${{ steps.updateVersion.outputs.PACKAGE_VERSION }}"
          git push --set-upstream origin ${{ steps.verifyBranch.outputs.BRANCH_NAME }}
          echo ::set-output name=NEW_BRANCH::true
      - name: Commit Existing Branch
        id: commitExistingBranch
        if: ${{ steps.verifyBranch.outputs.BRANCH_EXISTS == 'true' }}
        run: |
          git config --global user.name "kephman"
          git config --global user.email "kepher@gmail.com"
          git checkout ${{ steps.verifyBranch.outputs.BRANCH_NAME }}
          git merge master
          git commit -am "AUTO: Version update for ${{ steps.updateVersion.outputs.PACKAGE_VERSION }}"
          eval "git push"
      - name: Create Pull Request
        id: createPull
        if: ${{ steps.verifyBranch.outputs.BRANCH_EXISTS == 'false' }}
        uses: kephman/auto-version-node@v1.0.7
        with:
          access-token: ${{ secrets.ACTIONS_TOKEN }}
          branch-name: ${{ steps.verifyBranch.outputs.BRANCH_NAME }}
          package-version: ${{ steps.updateVersion.outputs.PACKAGE_VERSION }}
